server:
  port: 9269
spring:
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
  devtools:
    livereload:
      enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mashumabduljabbar/altera/tree/main/config
          clone-on-start: true