eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://15.207.72.135:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 15.207.72.135
